services:
  adguardhome:
    image: adguard/adguardhome
    container_name: AdGuard
    environment:
      TZ: "Europe/Paris"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3080:80/tcp"
      - "443:443/tcp"
      - "443:433/udp"
      - "3000:3000/tcp"

    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped


volumes:
  adguard_work:
  adguard_conf:
